import Freska from "../assets/Freska.png";
import Hero from "../assets/hero.png";
export const categoryAgency = [
  {
    nameCategory: "Full Service Agenchy",
    description: "A collection of full service agencies.",
    image: "",
    agencies: [
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Hero,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Hero,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Hero,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Hero,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Hero,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Hero,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Hero,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Hero,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Hero,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Hero,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Hero,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Hero,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Hero,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Hero,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Hero,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Hero,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Hero,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Hero,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Hero,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Hero,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Hero,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Hero,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Hero,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Hero,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Hero,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Hero,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 3",
        description: "Description of Agency 3",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 4",
        description: "Description of Agency 4",
        image: Freska,
        link: "",
      },
    ],
  },
  {
    nameCategory: "Wedding Organizers",
    description: "A collection of wedding organizers.",
    image: Freska,
    agencies: [
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },

      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 1",
        description: "Description of Agency 1",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 2",
        description: "Description of Agency 2",
        image: Freska,
        link: "",
      },
    ],
  },

  {
    nameCategory: "Social Organizers",
    description: "A collection of social organizers.",
    image: Freska,
    agencies: [
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
    ],
  },
  {
    nameCategory: "EO Spesialis MICE",
    description: "A collection of EO Spesialis MICE.",
    image: Freska,
    agencies: [
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
    ],
  },
  {
    nameCategory: "Brand Activation Agency",
    description: "A collection of Brand Activation Agency.",
    image: Freska,
    agencies: [
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
    ],
  },
  {
    nameCategory: "EO Virtual & Hybrid",
    description: "A collection of EO Virtual & Hybrid.",
    image: Freska,
    agencies: [
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 5",
        description: "Description of Agency 5",
        image: Freska,
        link: "",
      },
      {
        name: "Agency 6",
        description: "Description of Agency 6",
        image: Freska,
        link: "",
      },
    ],
  },
];
